### ISSUE TITLE
puppet-logstash produces a blank logstash.conf

### ISSUE THREAD

**Issue by wilkinsbrian** [elastic/puppet-logstash#162]
Puppet-logstash module seems to be looking for /etc/init/logstash, but I don't see anywhere that it is defined that this is required. I know you can add one per the README, but it didn't seem like it was required. From debug:

`/Stage[main]/Logstash::Service/Logstash::Service::Init[logstash]/File[/etc/init/logstash.conf]: Nothing to manage: no ensure and the resource doesn't exist`

When I do a run, I end up with a blank logstash.conf in my `/etc/logstash/conf.d` directory.

I have setup the configuration of my shipper using Hiera:

```
 classes:
   - os::repo
   - profiles::logstash::shipper

 logstash::configfile:
    'input_file':
       content: '/etc/puppet/modules/profiles/manifests/logstash/templates/input_file.erb'
       order:   '10'
```

My `profiles::logstash::shipper` is setup as:

```
  class profiles::logstash::shipper() {
     class { 'logstash':
        ensure  => 'present',
        version => '1.4.1-1_bd507eb',
        status  => 'enabled',
     }
    include logstash
  }
```

input_file.erb:

```
  input {
     file {
        type => "syslog"
        path => ["/var/log/secure", "/var/log/messages", "/var/log/syslog"]
        exclude => ["*.gz", "shipper.log"]
        sincedb_path => "/var/run/logstash/lssincedbs"
    }

    file {
        type => "logfile"
        path => ["/tmp/*.log"]
        sincedb_path => "/var/run/logstash/lssincedbs"
    }
 }
```

(I know this technically isn't an erb but it will be eventually)

Every time puppet agent does a catalog run, it produces an empty `logstash.conf` in `/etc/logstash/conf.d` on my agent acting as a shipper.

What did I do wrong? I am probably confused as I didn't understand something in the github documentation.
