### ISSUE TITLE
Inputs, codecs, filters, outputs config management

### ISSUE THREAD

**Issue by arioch** [elastic/puppet-logstash#211]
The lack of support to configure inputs, codecs, filters, outputs using the module seems to be a recurring topic. Personally it's driving me up to a point where I'd consider not using an upstream supported module anymore. But instead invest time and effort in rewriting a module I once maintained.

If a Puppet module doesn't do config management, what good is the module?

Is this something that will be supported (again, fdf7cab2bd33fc30ed4cea88c0540b1b6a6cc8ab) in the future? Would you consider accepting patches?

**Comment by cdenneen** [comment]
@arioch What's the issue with configuration pieces?

I have these in Hiera

```yaml
logstash_config:
  input_syslog:
    source: 'puppet:///files/logstash-repo/10syslog_input.conf'
    order: 10
  input_eventlog:
    source: 'puppet:///files/logstash-repo/10eventlog_input.conf'
    order: 10
  input_iis:
    source: 'puppet:///files/logstash-repo/10iis_input.conf'
    order: 10
  filter_apache:
    source: 'puppet:///files/logstash-repo/30apache_filter.conf'
    order: 30
  filter_syslog:
    source: 'puppet:///files/logstash-repo/30syslog_filter.conf'
    order: 30
  filter_iis:
    source: 'puppet:///files/logstash-repo/30iis_filter.conf'
    order: 30
  output_elastic:
    source: 'puppet:///files/logstash-repo/80elastic_output.conf'
    order: 80
```
