### ISSUE TITLE
Use an array from hiera to create config files

### ISSUE THREAD

**Issue by tobygale** [elastic/puppet-logstash#327]
Hello,

I would like to see functionality to pass `logstash::configfile` an array from hiera which would be subsequently used to populate a configuration file.

Consider the following:
```yaml
---
# some-node.yaml
ls_configs:
  heartbeat-input:
    content:
      - {
      -   heartbeat {}
      - }
```

```puppet
# my-manifest.pp
include ::logstash

$ls_configs = hiera_hash('ls_configs', {})
create_resources('logstash::configfile', $ls_configs)
```

I think this could be achieved by modifing line 50 in `manifests/configfile.pp` from:
```puppet
elsif($content) { $config = $content }
```

To something like:
```puppet
elsif($content) {
  if is_array($content) {
    $data = join($content, "\n")
    $config = "${data}\n"
  } else {
    $config = $content
  }
}
```

This could be merged as a patch release as it shouldn't break existing configurations.

I'm happy to submit a PR for this change and an associated test.

**Comment by jarpy** [comment]
Hi @tobygale. It seems you had a PR out for this but closed it? Did you get your problem resolved?

If it's still relevant, would it be better to pass a multi-line string from Hiera, rather than an array?

``` yaml
ls_configs:
  heartbeat-input:
    content: |
      {
        heartbeat {}
      }
```
